export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_LOADING = 'ORDER_CREATE_LOADING';
export const ORDER_CREATE_FAIL = 'PAYMENT_CREATE_FAIL';
export const ORDER_CREATE_INIT = 'ORDER_CREATE_INIT';

export const ORDER_LIST_LOADING = 'ORDER_LIST_LOADING';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DETAIL_LOADING = 'ORDER_DETAIL_LOADING';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL';
