export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_LOADING = 'ORDER_CREATE_LOADING';
export const ORDER_CREATE_FAIL = 'PAYMENT_CREATE_FAIL';
export const ORDER_CREATE_INIT = 'ORDER_CREATE_INIT';
